<a href="https://colab.research.google.com/github/wisdomscode/Deep-Learning-using-PyTorch/blob/main/tensor_operators.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
# Rnage of Number
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Reshape and View

reshape() and view() are used to change the shape of a tensor,

In [4]:
# Reshape
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
# Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
# view
my_torch3 = torch.arange(12)
my_torch3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
my_torch4 = my_torch3.view(3,4)
my_torch4

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Difference between Reshape and View

**1. view()**
* Returns a new tensor with a different shape but shares the same data (i.e., it is a view of the original tensor).
* It requires that the tensor is contiguous in memory. If not, you'll need to call .contiguous() before using view().

**2. reshape()**
* Returns a tensor with a new shape, but it may or may not share the same data as the original tensor.
* Unlike view(), reshape() automatically makes the tensor contiguous if needed.

Rashape and View can Update

When you make a change to the original tensor, the child or dependant tensor will be updated automatically

In [13]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
my_torch5[1] = 123
my_torch5

tensor([  0, 123,   2,   3,   4,   5,   6,   7,   8,   9])

In [16]:
my_torch6

tensor([[  0, 123,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

Slices - extracting part of a tensor

In [19]:
my_tensor7 = torch.arange(12)
my_tensor7

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
# Grab a specific item
my_tensor7[6]

tensor(6)

In [20]:
my_tensor8 = my_tensor7.reshape(3,4)
my_tensor8

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Get Items by column

In [30]:
my_tensor8[:,1]

tensor([1, 5, 9])

In [29]:
my_tensor8[:,2]

tensor([ 2,  6, 10])

In [28]:
my_tensor8[:,3]

tensor([ 3,  7, 11])

Get items by row

In [38]:
# get all rows
my_tensor8[:,:]

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [41]:
#get first row only
my_tensor8[:1,:]

tensor([[0, 1, 2, 3]])

In [42]:
# get second row only
my_tensor8[1:2,:]

tensor([[4, 5, 6, 7]])

In [44]:
# get from second to end
my_tensor8[1:,:]

tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [45]:
# get the last row
my_tensor8[-1:,:]

tensor([[ 8,  9, 10, 11]])