<a href="https://colab.research.google.com/github/wisdomscode/Deep-Learning-using-PyTorch/blob/main/tensor_math_operators.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [7]:
tensor_a = torch.Tensor([1,2,3,4,5])
tensor_b = torch.Tensor([6,7,8,9,10])

# tensor_a
# print()
# tensor_b

In [8]:
# Addtion
tensor_a + tensor_b

tensor([ 7.,  9., 11., 13., 15.])

In [9]:
tensor_a.add(tensor_b)

tensor([ 7.,  9., 11., 13., 15.])

In [10]:
# Subtraction
tensor_b - tensor_a

tensor([5., 5., 5., 5., 5.])

In [11]:
tensor_b.sub(tensor_a)

tensor([5., 5., 5., 5., 5.])

In [12]:
# multiplication
tensor_a * tensor_b

tensor([ 6., 14., 24., 36., 50.])

In [13]:
tensor_a.mul(tensor_b)

tensor([ 6., 14., 24., 36., 50.])

In [14]:
# division
tensor_b / tensor_a

tensor([6.0000, 3.5000, 2.6667, 2.2500, 2.0000])

In [15]:
tensor_b.div(tensor_a)

tensor([6.0000, 3.5000, 2.6667, 2.2500, 2.0000])

In [16]:
# Modulus - remainder
tensor_b % tensor_a

tensor([0., 1., 2., 1., 0.])

In [17]:
tensor_b.remainder(tensor_a)

tensor([0., 1., 2., 1., 0.])

In [18]:
# Exponential
tensor_a.pow(tensor_b)

tensor([1.0000e+00, 1.2800e+02, 6.5610e+03, 2.6214e+05, 9.7656e+06])

Reassignment

In [22]:
tensor_a = tensor_a + tensor_b
tensor_a

tensor([12., 14., 16., 18., 20.])

In [24]:
tensor_a.add_(tensor_b)
tensor_a

tensor([18., 21., 24., 27., 30.])